### ISSUE TITLE
Parquet Creation and Update failed in Prefect by Client not associated with a value

### ISSUE THREAD

**Issue by LeoLee-Xiaohu** [aodn/aodn_cloud_optimised#106]
We created a [Prefect flow](https://github.com/aodn/dataflow-orchestration/blob/feature/5819-use-cloud-optimised-lib/projects/cloud_optimised/cloud_optimised_update_flow.py) that used the cloud optimised repo to update parquet datasets. However, there is an error of `UnboundLocalError: cannot access local variable 'client' where it is not associated with a value` broke the prefect flow. 

Here is the error log in prefect: 
```
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/xiaohul/miniconda3/envs/cloud-optimised/lib/python3.11/site-packages/prefect/engine.py", line 894, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiaohul/miniconda3/envs/cloud-optimised/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiaohul/miniconda3/envs/cloud-optimised/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiaohul/AODN/dataflow-orchestration/projects/cloud_optimised/cloud_optimised_update_flow.py", line 40, in update_optimised
    cloud_optimised_creation(
  File "/home/xiaohul/miniconda3/envs/cloud-optimised/lib/python3.11/site-packages/aodn_cloud_optimised/lib/CommonHandler.py", line 617, in cloud_optimised_creation
    handler_instance.to_cloud_optimised(s3_file_uri_list)
  File "/home/xiaohul/miniconda3/envs/cloud-optimised/lib/python3.11/site-packages/aodn_cloud_optimised/lib/GenericParquetHandler.py", line 1097, in to_cloud_optimised
    client, cluster = self.create_cluster()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiaohul/miniconda3/envs/cloud-optimised/lib/python3.11/site-packages/aodn_cloud_optimised/lib/CommonHandler.py", line 248, in create_cluster
    client.forward_logging()
    ^^^^^^
UnboundLocalError: cannot access local variable 'client' where it is not associated with a value
```
It seems like that the [ClusterMode ](https://github.com/aodn/dataflow-orchestration/blob/93e0b39805069b051a6c927763a455e68a8f38aa/projects/cloud_optimised/cloud_optimised_update_flow.py#L46C1-L46C39)of `None` is not supported for parquet. It could be very helpful if @lbesnard could have a look on this.

**Comment by lbesnard** [comment]
@LeoLee-Xiaohu this should be fixed now with latest version. see for example the unittest now working without a cluster value
https://github.com/aodn/aodn_cloud_optimised/blob/main/test_aodn_cloud_optimised/test_generic_parquet_handler.py#L211

work is done here:
https://github.com/aodn/aodn_cloud_optimised/blob/main/aodn_cloud_optimised/lib/GenericParquetHandler.py#L1134

**Comment by LeoLee-Xiaohu** [comment]
[like]  Leo Li reacted to your message:
________________________________

**Comment by craigrose** [comment]
I'll closed this because no cluster mode seems to be working now.
